[build]
  command = "pnpm generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.13.1"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"